# Generated by Django 3.0 on 2020-02-11 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='architectorofficer',
            name='is_officer',
            field=models.BooleanField(default=False, help_text='How will you use ZANK?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='architectorofficer',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
