# Generated by Django 3.0.3 on 2020-03-01 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200227_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='architectorofficer',
            name='is_officer',
            field=models.BooleanField(default=False, help_text='True if you are a government compliance officer, and false otherwise.'),
        ),
    ]
