# Generated by Django 3.0.3 on 2020-02-26 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0003_auto_20200224_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Code officially active?'),
        ),
    ]
