# Generated by Django 3.0.3 on 2020-02-29 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('codes', '0004_code_is_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='posted_by',
            field=models.ForeignKey(blank=True, help_text='Officer who entered the code.', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
